# Generated by Django 4.2.28 on 2026-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default="Not Provided"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("paid", "paid"),
                    ("failed", "failed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="0000000000", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("shipped", "shipped"),
                    ("delivered", "delivered"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
